apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: {{ .Values.namespace }}
data:
  init.sql: |
    CREATE TABLE marks (
      id SERIAL PRIMARY KEY,
      name TEXT,
      marks INT
    );
