apiVersion: v1
kind: Secret
metadata:
  name: postgres-seceret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.database.PASSWORD }}
  POSTGRES_USER: {{ .Values.database.USER }}
  POSTGRES_DB: {{ .Values.database.DB_NAME}}
