apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: postgres-db
  ports:
  - port: {{ .values.image.port }}
    targetPort: {{ .values.image.port }}
