apiVersion: v1
kind: Secret
metadata:
  name: postgres-seceret
  namespace: {{ .values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .values.database.PASSWORD }}
  POSTGRES_USER: {{ .values.database.USER }}
  POSTGRES_DB: {{ .values.database.DB_NAME}}
