apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: grade-submission
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: student-grade-ui
  ports:
  - port: 80
    targetPort: 80
