apiVersion: v1
kind: Secret
metadata:
  name: student-grade-api-secret
  namespace: grade-submission
type: Opaque
data:
  DB_USER: {{ .values.secrets.DB_USER }}
  DB_PASS: {{ .values.secrets.DB_PASS }}
