apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-grade-ui
  namespace: grade-submission
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: student-grade-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: student-grade-ui
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: student-grade-ui
    spec:
      affinity:
       podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
         - labelSelector:
             matchExpressions:
             - key: "app.kubernetes.io/instance"
               operator: In
               values:
               - student-grade-ui
           topologyKey: "kubernetes.io/hostname" # Spreads pods across nodes
      containers:
      - name: student-grade-ui
        image: studentgrade.azurecr.io/frontend/frontend:v2
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "250Mi"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
