apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .value.namespace }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: student-grade-ui
  ports:
  - port: {{ .value.image.port }}
    targetPort: {{ .value.image.port }}
